# Exposes Ruby's internal implementation of strings. Something funny happens around length 23-24...
(1..50).each{|i| str="a"*i; t=Time.now; 10000.times{ str.gsub(/a/,'b') }; puts "#{i}, #{'#' * (300 * (Time.now-t))}"}
